name: matrix

on:
  push:

jobs:
  matrix-job:
    name: matrix job
    strategy:
      matrix:
        runner: [ubuntu-latest, windows-latest]
        pyhton-version: [3.11, 3.12, 3.13]
        include: 
         - runner: macros-latest
           python-version: 3.12
        exclude:
          - runner: windows-latest
            python-version: 3.13
    run-ons: ${{ matrix.runner }}
    steps: 
      - run: echo this job will run in python version ${{ matrix.python-version }}
